/*
This script contains all flavor text options as a list of possible settings, each consisting of a dictionary
of possible lines.
*/

const globalFlavorLines = [
    {
        "sundown1": ["Zwischen sanft wiegenden Weizenfeldern liegt ein Dorf, ruhig unter dem roten Himmel der untergehenden Sonne."],
        "sundown2": ["Im Abendrot versinkt die untergehende Sonne, während sich die Finsternis über die fernen Fichtenspitzen legt und langsam das Dorf erreicht."],
        "sunrise1": ["Der Hahn kräht und die ersten Sonnenstrahlen fallen warm auf die Weizenfelder, während das Dorf langsam erwacht.",
                     "Das Dorf erwacht, während Vögel fröhlich Weizenkörner von den Feldern picken und ihr Zwitschern die warme Morgenluft erfüllt."],
        "sunrise2": ["Das Dorf erwacht im sanften Nieselregen, während das leise Zwitschern der Vögel die trübe Stille durchbricht."],
        "villagewin": ["Eine warme Briese weht durch die laue Abendluft und der Gesang fröhlichen Dorfbewohner ist noch weit über die Weizenhügel zu hören. Die Welt ist wieder in Ordnung. "],
        "wwwin": ["Rot leuchtende Augen nähern sich vom Waldrand dem Dorf und ein letzter qualvoller Schrei hallt über die Weizenhügel, bevor die Stille der Nacht wieder einkehrt..."],
        "loverswin": ["Die beiden Liebenden sitzen glücklich mit den Beinen baumelnd auf dem dicken Ast der alten Eiche und beobachten wie langsam die rote Sonne hinter den Weizenhügeln verschwindet."],
        "nowin": ["Die tote Stille im Dorf wird einzig durch die an den bleichen Knochen nagenden Ratten unterbrochen..."],
        "discussion": ["Auf einem Hügel, unter der alten Eiche, versammelt sich das Dorf, die Blicke auf den dicken Ast gerichtet – wer wird heute an ihm hängen?"],
        "execution1": ["XY wird langsam zur Eiche geführt, die Schlinge um den Hals gelegt, das Dorf zieht ihn/sie zappelnd empor und nach kurzer Zeit baumelt sein/ihr toter Körper an der alten Dorfeiche.",
                       "Als das gesamte Dorf mit dem Finger auf XY zeigt, stürmt er/sie verzweifelt davon, doch Hund Michi ist schneller, beißt ihm/ihr in die Wade und zieht ihn/sie, zappelnd und schimpfend, zurück zur Eiche, wo XY gegen seinen/ihren Willen gehängt wird.",
                       "Als XY langsam an der Eiche hochgezogen wird, hören die Dorfbewohner ein knarzendes Geräusch, doch der dicke Ast der alten Eiche hält stand und trägt XY weiter, bis er/sie kläglich stirbt."],
        "execution2": ["Als XY langsam an der Eiche hochgezogen wird, hören die Dorfbewohner ein knarzendes Geräusch, und nach kurzer Zeit reißt der Strick – XY liegt schwer atmend auf dem Boden, benommen, aber am Leben.",
                       "Als das Dorf mit dem Finger auf XY zeigt, rennt er/sie panisch davon. Niemand ist schnell genug, ihn/sie einzuholen, und nach kurzer Zeit sieht das Dorf ihn/sie in den fernliegenden Fichten verschwinden – Glück gehabt."],
        "execution3": ["XY wird zur Eiche geführt und aufgeknüpft, zappelnd mit herausquellenden Augen, als plötzlich ein lautes Krachen ertönt und der Ast der Eiche abbricht... XY liegt schwer atmend auf dem Boden, aber immernoch lebendig."],
        "execution4": ["Als das Dorf XY ergreifen will, um ihn/sie zur Eiche zu führen, kreischt XY in hoher Stimme: \"Mein Vati wird euch jagen! Er ist der Großmagier von Ozelot!\" Die Menge verstummt, und XY wird widerwillig freigelassen."],
        "werewolves": ["Im Dorf ist ein Heulen aus dem fernen Wald zu hören – die Werwölfe sind auf der Jagd nach einem Opfer.",
                       "Die Stille der Nacht wird durch ein lautes Heulen aus den im Mondlicht erleuchteten Weizenfeldern durchbrochen – die Werwölfe sind erwacht und suchen nach einem Opfer."],
        "shadowwolf": ["Der Mond verdunkelt sich als der Schattenwolf erwacht, um auf dem Friedhof die Schatten der Toten zu beobachten."],
        "dirtywolf": ["Im Dorf ist ein Zischen und Sabbern zu hören, als der Räudige Wolf fürchterlich durch die Gassen schleicht."],
        "pig": ["Schmatzende und schlürfende Geräusche sind aus einer dunklen Gasse zu hören... Plötzlich verstummen sie und ein riesiger Schatten huscht hinfort."],
        "witch1": ["Die Hexe erwacht, beginnt mit ihrem schaurigen Hexentanz und singt laut ihre Zauberformeln: \"Rattenblitz und Spinnenzahn, schütze uns vor Wolfes Wahn!\" "],
        "witch2": ["\"Ziegenbein und Höllensaat, du seist verflucht und das Ende naht!\""],
        "priest": ["Der Priester wacht auf, um die Häuser seiner Lämmchen zu segnen."],
        "seer": ["Mit seinem dritten Auge blickt der Seher starr in die Seelen der Dorfbewohner. "],
        "necro": ["Inmitten der Weizenfelder führt der Nekromant sein verbotenes Ritual durch und blickt ins Reich der Toten."],
        "girl": ["Ein kleines Mädchen späht neugierig auf die im Mondschein erhellten Weizenfelder...."],
        "bitch": ["Ihren roten Rock tragend, streift die Dorfschlampe von Tür zu Tür und sucht nach einsamen Herzen."],
        "homeless": ["Stinkend und sabbernd schlurft der Obdachlose durch die Gassen und sucht nach einem Ort zum Pennen."],
        "clerk": ["Noch spät im Archiv wühlt sich der Beamte durch verschiedenste Akten."],
        "lotte": ["Ein markdurchdringender Schrei hallt durch das Dorf: \"Kreiiiiiiiiischhhhh!\". Fieselotte war für immer verstummt..."],
        "crossbow": ["XY taumelt blutend vom Waldrand zur alten Eiche, eine Armbrust in der Hand, das Dorf erstarrt vor Schreck."],
        "silence": ["Der mit dem Schweigetrank erwacht und überlegt, wem er/sie die ewige Stille einflößen soll."],
        "robber": ["Geschützt von der Dunkelheit, schleicht sich der Leichenfledderer auf den Friedhof und sucht nach den verbliebenen Schätzen der Toten. "],
        "dog": ["Hund Michi muss schon wieder pieseln! Er weckt seinen Besitzer und führt ihn auf eine interessante Spur."],
        "lovepot": ["Der Liebestrank, in rotem Glanz, wird zwei Glücklichen eingeflößt und weckt ein brennendes Verlangen."],
        "hatepot": ["Pechschwarz und blubbernd brodelt der Hasstrank – ein Schluck, und zwei Seelen brennen vor Zorn, bis nur noch eine von ihnen atmet."],
        "plague": ["Ein fürchterlicher Gestank dringt aus XYs Hütte und beim Öffnen der Tür stürmen hunderte Ratten heraus. Inmitten des Chaos liegt XYs lebloser Körper – übersät mit eitrigen Beulen..."],
        "woodworm": ["Der Hüter des Holzwurms brütet nachdenklich über dem Terrarium, während er seinen Wurm mit Sägemehl füttert.",
                    "Der Holzwurm schnurrt ganz entzückt, während ihn sein Besitzer mit Sägemehl füttert."],
        "woodwormgone": ["Der Besitzer des Holzwurms sucht verzweifelt nach seinem Haustier."],
        "doppel": ["<missing>"]
    },
    {
        "sundown1": ["Die letzten Sonnenstrahlen des sterbenden Tages brechen durch tief liegende Wolken, und trüber Nebel zieht über das Moor und zwischen die verschlagenen Hütten des Dorfes."],
        "sundown2": ["Drückende Stille legt sich über das Dorf, als dichter Nebel im fahlen Licht der untergehenden Sonne von den Tümpeln und Mooren aufsteigt und sich über das schlafende Dorf legt.",
                     "In Totenstille sinkt der Hochnebel herab auf das Dorf und im letzten Zwielicht befällt eine dunkle Vorahnung die Dorfbewohner."],
        "sunrise1": ["Die Morgenluft ist kühl und klar, und fahle Sonnenstrahlen dringen durch die hochliegenden Wolken.",
                     "Ein einsamer Spatz zwitschert in der Ferne, und im fahlen Sonnenlicht wird den Dorfbewohnern das Herz ein wenig leichter."],
        "sunrise2": ["Regen nieselt aus den tief hängenden Wolken auf den Marktplatz, und im fahlen Morgenlicht hängt ein moderiger Geruch über dem Dorf.",
                     "Ein starker Wind peitscht den Regen an die Fenster der Dorfbewohner und trägt einen faulen Geruch aus dem Moor heran."],
        "villagewin": ["Zum ersten Mal seit Tagen lichten sich die Wolken und süße Sonnenstrahlen tauchen das Dorf in ein goldenes Licht."],
        "wwwin": ["Ein markerschütterndes Heulen hallt über das Moor, und durch ein einziges Loch in der dichten Wolkendecke wirft der silberne Mond sein unheimliches Licht auf das Dorf."],
        "loverswin": ["Eingehüllt in dichte Mäntel stapft das Liebespaar durch den Regen und beginnt den beschwerlichen Weg fort aus dem Dorf und in ein neues Leben."],
        "nowin": ["Auf den Gräbern der Toten blüht eine einsame Lilie, eine letzte Erinnerung an das lebhafte Dorf, das hier einmal stand."],
        "discussion": ["Zwischen Karren voll Torf und windschiefen Marktständen finden sich die Dorfbewohner langsam auf dem Dorfplatz ein.",
                       "Eingehüllt in dicke Mäntel stapfen die Dorfbewohner einer nach dem anderen verstohlen auf den Marktplatz."],
        "execution1": ["Ein klammer Strick wird XY um den Hals gelegt, und das morsche Holz knirscht, als das Seil sich spannt und den leblosen Körper knapp über dem Boden hält.",
                       "Ein klammer Strick wird XY um den Hals gelegt, er/sie fällt, und mit einem lauten Krachen bricht sein/ihr Genick."],
        "execution2": ["Ein klammer Strick wird XY um den Hals gelegt, er/sie fällt, doch das vermoderte Seil kann sein/ihr Gewicht nicht halten und er/sie stürzt zu Boden."],
        "execution3": ["Ein klammer Strick wird XY um den Hals gelegt, er/sie fällt, und mit einem lauten Krachen zerbirst der Galgen in hundert madenzerfressene Holzsplitter."],
        "execution4": ["Gerade als die Entscheidung gefällt wird, steigt XY auf einen Holzkarren hinauf und schreit: \"Ich bin der Neffe des Barons! Wenn er hiervon erfährt, lässt er euch alle Hinrichten!\""],
        "werewolves": ["Die Nebelschwaden werden dunkler und ein süßer Geruch zieht durch die Gassen: der Gestank des Todes.",
                       "Die Tümpel dampfen und Regenwürmer verziehen sich im Boden, als rote Augen in den dunkelsten Ecken des Dorfs erwachen."],
        "shadowwolf": ["Die Geister der Toten wimmern leise, als sich Irrlichter aus den Tiefen des Moores erheben und den Schattenwolf ins Reich der Toten führen."],
        "dirtywolf": ["Giftiger Dampf steigt aus dem Morast auf, und selbst die Ratten fliehen als der räudige Wolf ins Dorf schleicht."],
        "pig": ["Die schweren Schritte eines übergroßen Wolfes im Matsch werden vom dichten Nebel erstickt, und ein unglücklicher Dorfbewohner vernimmt das Knurren und Grunzen des Schweins."],
        "witch1": ["Allein in ihrer Kräuterhütte liest die Hexe in ihrem verbotenen Buch:<br> \"Ein Absud der Schwertlilienwurzel heilt jedes Leiden...\""],
        "witch2": ["Sie blättert um:<br> \"... doch wer ihre Blüten kostet, der tut bald seinen letzten Atemzug.\""],
        "priest": ["Mit nichts als seiner Kutte, dem Weihwasser in der einen, und dem heiligsten Kreuz in der anderen Hand, schreitet der Priester durch die Straßen."],
        "seer": ["Im Kristall der Kugel lichten sich die Nebel der Welt, und in einem Moment der Klarheit erblickt der Seher die schrecklichen Geheimnisse des Dorfes."],
        "necro": ["In einen schwarzen Mantel gehüllt folgt der Nekromant den Irrlichtern tief ins Moor, um den Stimmen der Toten zu lauschen."],
        "girl": ["Ein kleines Mädchen kann nicht schlafen und blickt verstohlen durch die beschlagenen Fenster ihres Zimmers auf den Dorfplatz."],
        "bitch": ["In ihrem dünnen Gewand eilt die Dorfschlampe durch den Matsch, in der Hoffnung, ihre Stiefel nicht allzu dreckig zu machen."],
        "homeless": ["In klammen Lumpen und mit eisigen Händen schleppt sich der Obdachlose durch die Straßen auf der Suche nach einem trockenen Ort zum Pennen."],
        "clerk": ["Im Dachboden des höchsten Hauses wühlt der Beamte durch seine Listen, die er selbst hier oben nicht vor dem Schimmel retten konnte."],
        "lotte": ["Die Raben flattern auf, als ein fieses Kreischen über das Moor hallt."],
        "crossbow": ["In einer Lache aus Blut und Schlamm kniend, erhebt sich XY ein letztes Mal und feuert seine Armbrust ab."],
        "silence": ["Leise schleicht sich ein Mann hinaus zu dem Tümpel hinter seiner Hütte, um seinen Vorrat an Schierlingskraut aufzustocken und damit dem Geschwätz seiner Nachbarn endlich Einhalt zu gebieten."],
        "robber": ["Mit Laterne, Schaufel und einem heiligen Rosenkranz zum Schutz vor den Irrlichtern wagt sich der Leichenfledderer auf den Friedhof."],
        "dog": ["Keiner hat eine feinere Nase als Michi, und zwischen dem Moder und Gestank des Sumpfes erschnüffelt er eine interessante Fährte."],
        "lovepot": ["Im süßen Nektar der Seerose spiegelt sich das Verlangen aller einsamen Herzen, doch welche zwei werden davon kosten dürfen?"],
        "hatepot": ["Nichts schürt Hass besser als Paranoia, und nichts macht paranoider als ein süß-bitterer Tropfen Tollkirschsaft."],
        "plague": ["Im Licht des sterbenden Tages beginnt XYs Leiche auf dem Dorfplatz zu zittern, und aus den eitrig-schwarzen Beulen erheben sich mit einem gewaltigen Summen hunderte hungrige Stechmücken."],
        "woodworm": ["Der Holzwurm kriecht verzückt zu dem saftigen Stück Holz, das sein Besitzer für ihn gesammelt hat.",
                    "Der Besitzer des Holzwurms beobachtet seinen Wurm: bald ist er groß genug, seinen Plan in die Tat umzusetzen."],
        "woodwormgone": ["Nun, da sein meisterhafter Plan funktioniert hat, verfeuert der ehemalige Besitzer des Holzwurms das Holz seines Terrariums im Ofen."],
        "doppel": ["Im Dunkeln legt der Doppelgänger seine Kleider ab und steigt hinab ins eisige Wasser des Moores. Momente vergehen, und im grünen Schimmer der Irrlichter steigt plötzlich eine neue Gestalt aus dem Wasser."]
    }
]

