const globalFlavorLines = [
    {
        "sundown1": ["Das Dorf liegt ruhig unter dem roten Himmel der untergehenden Sonne."],
        "sundown2": ["Die Sonne geht unter und Finsternis legt sich über das Dorf."],
        "sunrise1": ["Der Morgen graut und die ersten Sonnenstrahlen fallen auf das friedlich ruhende Dorf."],
        "sunrise2": ["Eine rot aufgehende Sonne wirft bedrohliche Schatten auf das Dorf."],
        "villagewin": ["Ein süßer Wind weht über das Dorf, als die Dorfbewohner sich erschöpft auf dem Marktplatz versammeln - die Gefahr ist gebannt."],
        "wwwin": ["Der Mond senkt sich über das Dorf und ein grausiges Heulen ertönt über dem nun leeren Dorf - die Werwölfe haben ihr Ziel erreicht."],
        "loverswin": ["Erschüttert von den Ereignissen der letzten Tage macht sich das Liebespaar auf, das nun leere Dorf zu verlassen und in ein neues Leben aufzubrechen."],
        "discussion": ["Die Dorfbewohner versammeln sich auf dem Marktplatz."],
        "execution1": ["XY wird an den Galgen geführt und unter betroffenem Schweigen gehängt."],
        "execution2": ["XY fällt, der Strick spannt sich - und reißt. Er liegt prustend am Boden, hat aber überlebt."],
        "execution3": ["XY fällt, der Strick spannt sich - und mit einem morschen Krachen bricht der Galgen."],
        "execution4": ["Noch bevor XY erfasst werden kann, hebt er seine Hand und alle sehen den Siegelring: \"Wenn ihr mich hängt, wird meine Familie euch alle holen!\""],
        "werewolves": ["Im Licht des Mondes hallt ein heulen über das Dorf und Schatten schleichen durch die Gassen."],
        "shadowwolf": ["Die Schatten werden dunkler und ein Wolf blickt in das Reich der Toten."],
        "dirtywolf": ["Ein giftiger Gestank zieht durchs Dorf, als der Schatten eines Wolfes auf der Suche nach einem besonderen Opfer durchs Dorf zieht."],
        "pig": ["Ein knurrendes Grunzen ertönt, als ein Wolf...? nein ein Schwein...!? sich auf den Straßen suhlt und anderer Leute Habseligkeiten frisst."],
        "witch1": ["Die Hexe rührt verzückt in ihrem Kessel: \"Ringelblume, Mariendistel, Johanniskraut ... und ein Glas voll Krötenschleim!\""],
        "witch2": ["Mit leuchtenden Augen greift sie zu ihren besten Zutaten: \"Eisenhut, Vogelbeeren und ein wenig Fliegenpilz!\""],
        "priest": ["Mit Kreuz und heiligem Wasser segnet der Priester ein Haus."],
        "seer": ["Im Nebel der Kristallkugel erblickt der Seher die Geheimnisse des Dorfes: ein rotes Auge, ein schwarzer Pelz..."],
        "necro": ["Bei Kerzenschein und Weihrauch tanzen die Toten zur Stimme des Nekromanten."],
        "girl": ["Ein kleines Mädchen hat zu viel Angst zum Schlafen und blickt heimlich hinaus auf den Dorfplatz."],
        "bitch": ["Auf der Suche nach einem neuen Kunden zieht die Dorfschlampe von Tür zu Tür. Oder bleibt sie doch zu Haus?"],
        "homeless": ["In Erwartung der eisigen Nacht sucht der Obdachlose einen Ort zum Pennen."],
        "clerk": ["Noch spät im Archiv prüft der Beamte die Richtigkeit der Dorfchronik."],
        "lotte": ["Kreiiiiiiiiiiisch!"],
        "crossbow": ["Schwerverletzt schafft es XY, noch einen Bolzen in seine Armbrust einzulegen."],
        "silence": ["Einst erhielt XY von einem Alchemisten einen Trank, der ewige Stille versprach. War nun die Zeit dafür gekommen?"],
        "robber": ["Mit Spitzhacke und Schaufel macht sich XY auf, im Dunkel der Nacht den Friedhof umzugraben."],
        "dog": ["Als Michis Besitzer noch spät mit ihm Gassi geht, erschnuppert er auf einmal eine interessante Spur..."],
        "lovepot": ["XY wollte die beiden schon immer verkuppeln, doch mit dem Trank, den er kürzlich von der Hexe erwarb, bietet sich nun die perfekte Gelegenheit..."],
        "hatepot": ["Schadenfroh holt XY seinen Trank aus dem Keller - wer soll sich hassen, und wer wird seinen Hass überleben?"],
        "plague": ["Der süße Geruch des Todes wabert über das Dorf, als die Eiterblasen des Verstorbenen platzen und Krankheit das Dorf befällt."],
        "woodworm": ["XY brütet nachdenklich über dem Terrarium, während er seinen Wurm mit Sägemehl füttert."],
        "woodwormgone": ["Traurig sitzt XY an seinem leeren Terrarium. Wo mag sein Wurm nun sein? Geht es ihm jetzt besser?"]
    }
]

